name: cu118
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=mkl
  - brotli-python=1.0.9=py39h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.1.31=hbd8a1cb_1
  - certifi=2025.1.31=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.2=pyhd8ed1ab_1
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.6=3
  - debugpy=1.8.14=py39hf88036b_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py39h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py39h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.29.5=pyh3099207_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.4=py39h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - krb5=1.21.3=h143b758_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.11.0.15=0
  - libcurand=10.3.7.37=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgomp=14.2.0=h767d61c_2
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.8.0.86=0
  - libnsl=2.0.1=hd590300_0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=h4ab18f5_6
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py39h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py39h06a4308_0
  - numpy=1.24.3=py39h14f4228_0
  - numpy-base=1.24.3=py39h31eccc5_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.5.0=h7b32b05_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=10.4.0=py39h5eee18b_0
  - pip=24.2=py39h06a4308_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.18=h0755675_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.9=7_cp39
  - pytorch=2.0.1=py3.9_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py39h06a4308_0
  - setuptools=72.1.0=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.12=py39h06a4308_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.0.2=py39_cu118
  - torchvision=0.15.2=py39_cu118
  - tornado=6.4.2=py39h8cd3c5a_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - urllib3=2.2.2=py39h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.43.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h3b0a872_7
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.5=hc292b87_2
  - pip:
      - absl-py==2.2.2
      - addict==2.4.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - async-timeout==4.0.3
      - attrs==24.2.0
      - autograd==1.7.0
      - autograd-gamma==0.5.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - blessed==1.21.0
      - causal-conv1d==1.4.0
      - click==8.1.8
      - cmake==3.30.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dgl==2.1.0
      - docopt==0.6.2
      - ecos==2.0.14
      - einops==0.8.0
      - einops-exts==0.0.4
      - eval-type-backport==0.2.2
      - fastjsonschema==2.21.1
      - fonttools==4.53.1
      - formulaic==1.0.2
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gpustat==1.1.1
      - grpcio==1.71.0
      - h5py==3.11.0
      - huggingface-hub==0.24.6
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.4
      - info-nce-pytorch==0.1.4
      - interface-meta==1.3.0
      - ipython==8.12.3
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.5
      - lifelines==0.29.0
      - lightning-utilities==0.11.6
      - lit==18.1.8
      - llvmlite==0.43.0
      - mamba-ssm==2.2.2
      - markdown==3.8
      - matplotlib==3.9.2
      - mistune==3.0.2
      - multidict==6.1.0
      - nbclient==0.10.1
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - ninja==1.11.1.1
      - numba==0.60.0
      - numexpr==2.10.2
      - nvidia-ml-py==13.580.65
      - nystrom-attention==0.0.12
      - opencv-python==4.10.0.84
      - openslide-python==1.3.1
      - osqp==0.6.7.post3
      - packaging==24.1
      - pandas==2.2.2
      - pandas-flavor==0.6.0
      - pandocfilters==1.5.1
      - patsy==0.5.6
      - pingouin==0.5.4
      - pipreqs==0.5.0
      - platformdirs==4.3.6
      - prompt-toolkit==3.0.48
      - propcache==0.2.0
      - protobuf==5.29.2
      - psutil==6.1.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pygments==2.18.0
      - pynndescent==0.5.13
      - pyparsing==3.1.4
      - pytz==2024.1
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - qdldl==0.1.7.post4
      - referencing==0.35.1
      - regex==2024.7.24
      - rpds-py==0.22.3
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - safetensors==0.4.4
      - scikit-learn==1.6.1
      - scikit-survival==0.23.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - sentry-sdk==2.43.0
      - smmap==5.0.2
      - soupsieve==2.6
      - statsmodels==0.14.2
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - timm==1.0.3
      - tinycss2==1.4.0
      - tokenizers==0.20.3
      - torch-geometric==2.6.1
      - torchdata==0.8.0
      - torchmetrics==1.4.1
      - tqdm==4.66.5
      - transformers==4.46.0
      - triton==2.1.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2024.1
      - umap==0.1.1
      - umap-learn==0.5.9.post2
      - wandb==0.22.3
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - wrapt==1.16.0
      - xarray==2024.7.0
      - yarg==0.1.9
      - yarl==1.17.1
      - zipp==3.20.1
prefix: /home/qiyuan/.conda/envs/cu118
